### ISSUE TITLE
[BUG] Cant' see the whole code when insert a new row

### ISSUE THREAD

**Issue by Sukaato** [DataflareApp/Dataflare#1]
### Describe the bug

![image](https://github.com/DataflareApp/Dataflare/assets/44368476/05a60b27-e473-4dc6-bb9c-543ec89a69ec)

When you have too many columns and you want to display the INSERT query, the code isn't scrollable.

### Platform and Database

```text
Windows 11 22H2
MariaDB
```

**Comment by wyhaya** [comment]
Fixed in next version
