### ISSUE TITLE
[Feature Request] Support LibSQL (SQLite over https)

### ISSUE THREAD

**Issue by jasongitmail** [DataflareApp/Dataflare#10]
### Describe the solution you'd like

This DB client is looking great!

[Turso](https://turso.tech/) has launched a DB that is getting very popular. It's based on [libsql](https://github.com/tursodatabase/libsql).

There is no support for LibSQL yet in TablePlus or any other desktop clients that I know. It'd very useful and a unique feature for Dataflare.

I'm not affiliated with Turso. Just a user.

**Comment by wyhaya** [comment]
@jasongitmail I have completed the support for `libSQL` in Dataflare, and it will be available for use in the next version.

Support: `Local connection` `Remote connection`
Unsupported: `sync connection`

**Comment by jasongitmail** [comment]
Amazing!

**Comment by wyhaya** [comment]
libSQL is now available on `macOS` and `Linux`.

**Comment by jasongitmail** [comment]
Thanks for adding it!

**Comment by wyhaya** [comment]
libSQL is now available on `Windows`
