### ISSUE TITLE
[Feature Request] Count the number of columns in the table

### ISSUE THREAD

**Issue by sajeisson** [DataflareApp/Dataflare#100]
### Describe the solution you'd like

It would be important to include, within the table summary, the number of columns that are created.

![Table](https://github.com/user-attachments/assets/8d109a82-d15c-45b7-b752-a02fd2fef043)

**Comment by wyhaya** [comment]
@sajeisson  Thank you for your feedback! This will be included in the next version!

**Comment by wyhaya** [comment]
`v1.8.1` has been released!

![footer](https://github.com/user-attachments/assets/4b446e0b-f407-4d43-a12b-a39000a542ae)

**Comment by sajeisson** [comment]
Excellent!
