### ISSUE TITLE
[BUG] All content dissapears

### ISSUE THREAD

**Issue by danielqba** [DataflareApp/Dataflare#102]
### Describe the bug

I can see the databases and tables. I can even manage connections. But as soon as I click a table, all content disappears. All panels go away (see screenshot)

![Screenshot from 2024-09-25 15-05-42](https://github.com/user-attachments/assets/d31463f5-096c-4477-a4cf-c52e0e28b7b9)
All OK in this screen, as soon as I click a table, I get the next one.

![Screenshot from 2024-09-25 15-05-50](https://github.com/user-attachments/assets/09aa7de1-b7b4-45dc-9ed1-ad91e8039d50)

### Platform and Database

```text
OS openSUSE Tumbleweed 64-bit GNOME 46
Windowing System: Wayland
Kernel Version: Linux 6.10.11-1-default
```

**Comment by wyhaya** [comment]
Hi @danielqba, thank you for your report.
We have just released a new version `v1.8.3` that upgrades the version of `webkitgtk`, and this error has been fixed.
This was caused by Dataflare using an incompatible Web API.
