### ISSUE TITLE
[BUG] The page number should be reset when a new search is performed.

### ISSUE THREAD

**Issue by AprilNEA** [DataflareApp/Dataflare#104]
### Describe the bug

The page number should be reset when a new search is performed.

### Platform and Database

```text
MacOS, PostgreSQL
```

**Comment by wyhaya** [comment]
@AprilNEA Thanks, this will be fixed in the next version.

**Comment by wyhaya** [comment]
Version `v1.9.0` has just been released, and this issue has been fixed! Thanks.
