### ISSUE TITLE
[BUG] 查询结果区域最大展示面积过小

### ISSUE THREAD

**Issue by 201307** [DataflareApp/Dataflare#107]
### Describe the bug

问题描述：执行查询语句后，查询结果区域最大只能占用整个窗口的一半左右
软件版本：1.8.4
运行平台：Windows 10 专业版 22H2 19045.4780
问题截图：
![data_bug](https://github.com/user-attachments/assets/f1ad3c60-919b-4f07-a01c-4d78f6336e41)

### Platform and Database

```text
Windows 10 专业版 22H2 19045.4780，MySQL
```

**Comment by wyhaya** [comment]
感谢反馈，这个问题会在以后的版本中修复！

**Comment by wyhaya** [comment]
刚刚发布了 `v1.9.2`, 已修复
