### ISSUE TITLE
[Feature Request] Change color theme manually

### ISSUE THREAD

**Issue by 2Pacalypse-** [DataflareApp/Dataflare#12]
### Describe the solution you'd like

I assume the color theme is based on your system preferences, but it would've been nice to be able to change it manually from within the application as well.

Thanks, the app seems great!

**Comment by wyhaya** [comment]
Currently only Windows system do not support manual theme switching, I have tried several times, but I think it is a bit difficult 😓

Upstream: [tauri-plugin-theme](https://github.com/wyhaya/tauri-plugin-theme)

**Comment by wyhaya** [comment]
A new version has been released which now allow manual switching of theme.
But it's not perfect (the app will be restarted after switching)

**Comment by 2Pacalypse-** [comment]
Works great, thank you!
