### ISSUE TITLE
[BUG] Cannot connect to database over SSH Tunnel/Proxy

### ISSUE THREAD

**Issue by wyze** [DataflareApp/Dataflare#13]
### Describe the bug

I am using Key authentication with a username and no password.

Here is the error it gives when testing the connection:

```
error communicating with database: Connection reset by peer (os error 54)
```

I've used other software to connect to the remote database without issue.

### Platform and Database

```text
Running in Docker on Linux, postgres 16.
```

**Comment by wyhaya** [comment]
This error message isn't obvious, but it's most likely the result of a ssh authentication failure or a failure to open a tcp tunnel, I'll look into it, thanks!

**Comment by wyhaya** [comment]
@wyze  A new version has just been released, which includes clearer error messages. You can give it another try.

**Comment by wyze** [comment]
Works now without issue. Thanks a bunch for the lighting fast fix!
