### ISSUE TITLE
[Feature Request] confirm field update

### ISSUE THREAD

**Issue by CraysCA** [DataflareApp/Dataflare#14]
### Describe the solution you'd like

When an update is made, have a button to confirm the changes and not update them directly, this as a security layer for the human factor

**Comment by wyhaya** [comment]
Update table column? I plan to redesign it

**Comment by CraysCA** [comment]
[image: image.png]
I was referring more than anything to this, being able to update several
fields and in the end confirming it and not updating them directly when
changing each field

**Comment by wyhaya** [comment]
Completed!

https://github.com/DataflareApp/Dataflare/assets/23690145/5647b4cc-0e73-47dc-ac37-793ca1221048
