### ISSUE TITLE
[Feature Request] Add Duplicate table functionality

### ISSUE THREAD

**Issue by ed1808** [DataflareApp/Dataflare#15]
### Describe the solution you'd like

In macOS when I make a click with two fingers to show the contextual menu over a table, there's no option to duplicate the table.

![Captura de Pantalla 2023-11-01 a la(s) 5 44 59 p m](https://github.com/DataflareApp/Dataflare/assets/122028804/904de0cf-7682-4247-815d-be15e28a94d0)

It would be great if that option could be added.

Here's an example of what I mean:

![Captura de Pantalla 2023-11-01 a la(s) 5 49 55 p m](https://github.com/DataflareApp/Dataflare/assets/122028804/473b4ef3-4e3d-4ec7-b454-d449a9140dc6)

**Comment by wyhaya** [comment]
It has been solved in the new version released!
