### ISSUE TITLE
[Feature Request] Add support for Public Key SSH connection

### ISSUE THREAD

**Issue by igorer88** [DataflareApp/Dataflare#17]
### Describe the solution you'd like

I'm trying to connect to an AWS aurora instance through SSH with a **Public Key (.pem)**
But it seams that the only option that it is available is through a **Private Key (.key)**

<img width="369" alt="imagen" src="https://github.com/DataflareApp/Dataflare/assets/6375299/b8cc0279-6911-498c-8143-3b7ad92bf926">

<img width="369" alt="imagen" src="https://github.com/DataflareApp/Dataflare/assets/6375299/49669c0a-840f-4562-bf1e-94c0ac7e4eea">

<img width="259" alt="imagen" src="https://github.com/DataflareApp/Dataflare/assets/6375299/229bf551-96c1-4fff-8083-ca765a6d5dbb">

**Comment by wyhaya** [comment]
Added, `RSA` key type will be supported starting from next version

**Comment by wyhaya** [comment]
This problem has been solved in the new version just released!

**Comment by igorer88** [comment]
Thanks! 🚀
