### ISSUE TITLE
[BUG] postgreSQL connection

### ISSUE THREAD

**Issue by djmashe** [DataflareApp/Dataflare#18]
### Describe the bug

error returned from database: 3 is outside the valid range for parameter "extra_float_digits" (-15 .. 2)

### Platform and Database

```text
windows 10, postgreSQL 10
```

**Comment by wyhaya** [comment]
Thanks for the report, can you provide more detailed information?
I would like to know what and where this problem occurs

**Comment by djmashe** [comment]
![Sin título](https://github.com/DataflareApp/Dataflare/assets/1840533/4627e894-1737-4d47-8f57-7e861b5fbe44)

When I try to connect with "Dataflare" I get this message.

But if I use another client, for example "pgAdmin", I can connect perfectly.

**Comment by wyhaya** [comment]
Thanks, it will be fixed in the next version!

**Comment by wyhaya** [comment]
This issue has been fixed!

**Comment by djmashe** [comment]
Yes, now the connection works with the new version. 
Thank you!
