### ISSUE TITLE
[BUG] can't select any db in New Connection select

### ISSUE THREAD

**Issue by CanRau** [DataflareApp/Dataflare#20]
### Describe the bug

Maybe the app just doesn't work on my OS (macOS 11.7.10 BigSur)?

But when opening, and trying to select a database to create a new connection nothing happens, also tried using keyboard just in case.

### Platform and Database

```text
macOS 11.7.10 BigSur
```

**Comment by wyhaya** [comment]
I've never done any testing on macOS `11.x`. This looks the same as #19, whenever a connection is created, a random UUID is generated, `randomUUID()` has compatibility issues on older system.

**Comment by ZhengXiaowei** [comment]
same issue

platform: macOS 11.2.3 BigSur

**Comment by wyhaya** [comment]
Hi, @CanRau @ZhengXiaowei
I just released a new version that should fix this problem, can you guys try it again?

**Comment by ZhengXiaowei** [comment]
> Hi, @CanRau @ZhengXiaowei I just released a new version that should fix this problem, can you guys try it again?

it's ok, thx~

**Comment by CanRau** [comment]
Wow that was insanely quick 🏃🏼💨
