### ISSUE TITLE
[BUG] Can't change record values from UI view (Postgres)

### ISSUE THREAD

**Issue by coluccini** [DataflareApp/Dataflare#22]
### Describe the bug

Every time I change the value of a record from the table content view UI and saved I get a "Primary key not unique".
This happens even with simple string changes on a varchar. If I made the same change via SQL sentence it get saved without problem at all.

I made a video showing the issue:

https://github.com/DataflareApp/Dataflare/assets/20334179/cdfed43a-3ff1-4da5-a096-568411097d13

### Platform and Database

```text
OS: MacOs 13
DB: postgres 9.5
```

**Comment by wyhaya** [comment]
@coluccini  Currently, this is intentional, regardless of modifying any values, it is necessary to ensure that there is only one primary key in the table. This is to prevent accidental modification of other rows. 

```ts
if (keys.length === 0) {
    throw Error('Primary key not found')
}
if (keys.length > 1) {
    throw Error('Primary key not unique')
}
```
In the future, this restriction will be removed.

**Comment by coluccini** [comment]
So I will never be able to edit data from the UI? Just through SQL sentences?

**Comment by wyhaya** [comment]
This restriction will be removed in the next version
