### ISSUE TITLE
[Feature Request] Support Libsql/Turso specific features

### ISSUE THREAD

**Issue by ansarizafar** [DataflareApp/Dataflare#23]
### Describe the solution you'd like

Please provide support for Libsql specific features like 
* ALTER TABLE extension for modifying column types and constraints
* Randomized ROWID
https://github.com/tursodatabase/libsql

**Comment by wyhaya** [comment]
A new version has just been released, now you can use the extension of libsql

**Comment by ansarizafar** [comment]
How can we use Randomized ROWID option with UI when creating a new table?

**Comment by wyhaya** [comment]
I'm thinking of redesigning the "create table UI", now you can only create tables with random rowid via SQL.
