### ISSUE TITLE
[Feature Request] If there are no records in the table, still show the structure

### ISSUE THREAD

**Issue by santisemhan** [DataflareApp/Dataflare#27]
### Describe the solution you'd like

Now when you execute a query and there are no rows to display it says "no rows", it would be nice to be able to see the table with empty rows.

![image](https://github.com/DataflareApp/Dataflare/assets/58712215/e3a9b90c-2e80-4406-9a5e-91c9c4bac53f)

**Comment by wyhaya** [comment]
Thanks, in the next version it will show the columns!

<img width="898" alt="Preview" src="https://github.com/DataflareApp/Dataflare/assets/23690145/b68e6ae1-623d-42d4-929a-d8b18b6b9eb1">

**Comment by wyhaya** [comment]
New version has been released!
