### ISSUE TITLE
File Script

### ISSUE THREAD

**Issue by diegoinost02** [DataflareApp/Dataflare#29]
### Describe the solution you'd like

I'm unable to locate the option to save an .sql script

**Comment by wyhaya** [comment]
Are you referring to saving the `Query` as a `.sql` file? There is currently no such option. I will add an option like this

**Comment by diegoinost02** [comment]
If that's what I meant, it's what I would need to use Dataflare as the main IDE.

**Comment by wyhaya** [comment]
In the new version, I added `Export` menu, which can export `Query` to local file.
I don't quite understand what you mean, if that's not what you want, please reopen the issue.

**Comment by diegoinost02** [comment]
Yes! That's what I meant, thank you very much! I'll start using this as my main IDE. The only thing I would be missing is a way to view entity-relationship diagrams, but I'm not in a hurry for that.

**Comment by lancelotly** [comment]
### [Feature Request]
Is it possible to open and modify the original SQL file?
As I edit the sql file imported from the local folder, the original file is not updated. Would you please consider such a feature? (Like open, edit, save, and keep a record of the sql file.)
Thanks for your consideration.

@wyhaya

**Comment by wyhaya** [comment]
@lancelotly Not currently supported.
Our main focus at the moment is to release 1.0 as soon as possible, and I'll look into these bits and pieces once it's stabilized.
