### ISSUE TITLE
[BUG] can't close window in fullscreen mode

### ISSUE THREAD

**Issue by DongHY1** [DataflareApp/Dataflare#30]
### Describe the bug

![CleanShot 2023-11-17 at 10 38 39](https://github.com/DataflareApp/Dataflare/assets/73568310/a8cb42a3-e876-48ec-8fac-78c4f8913ef2)

### Platform and Database

```text
Intel macOS 14.0 MySQL 8.0
```

**Comment by wyhaya** [comment]
Thanks, it will be fixed in the next version

**Comment by wyhaya** [comment]
A new version has been released!
