### ISSUE TITLE
On MacOS，there are no syntax highlighting and autocomplete suggestions


version：0.3.0
os：Sonoma 14.0

### ISSUE THREAD

**Issue by xHugh** [DataflareApp/Dataflare#32]

**Comment by wyhaya** [comment]
What database are you using? Which version?

**Comment by xHugh** [comment]
> What database are you using? Which version?

MySQL 5.7.30  aliyun rds

**Comment by wyhaya** [comment]
```sql
SELECT word FROM information_schema.keywords;
```

Dataflare uses this SQL to get keywords from the database, which is a error on `MySQL 5.7`.

```
Unknown table 'keywords' in information_schema`
```

It will be fixed in the next release.
