### ISSUE TITLE
[Question] Can't find way to import sql file.

### ISSUE THREAD

**Issue by boomNDS** [DataflareApp/Dataflare#37]
### What is your question?

I try to import my sql file, found export but where is import  feature?

**Comment by wyhaya** [comment]
Thanks, right now it's not possible to import SQL file to Query, I'll add one in the next version.

**Comment by boomNDS** [comment]
Noted Thxx

**Comment by wyhaya** [comment]
New version has been released!

https://github.com/DataflareApp/Dataflare/assets/23690145/3d002e42-b665-4a7a-b0e3-d31073c43a93
