### ISSUE TITLE
[Feature Request] Drag and drop sql script files

### ISSUE THREAD

**Issue by carloscv97** [DataflareApp/Dataflare#38]
### Describe the solution you'd like

I don't know if it already has this function, and if it does it doesn't work correctly, but it would be great to add the drag and drop sql script files function to simplify the function of importing scripts that has to be done manually

**Comment by wyhaya** [comment]
Thanks, it's a missing feature, I'll add it!

**Comment by wyhaya** [comment]
Completed!

https://github.com/DataflareApp/Dataflare/assets/23690145/f11593cb-6bb5-43c9-82e9-8d847f1dd3f8

**Comment by carloscv97** [comment]
Thank you for taking this suggestion @wyhaya 

Keep it up
