### ISSUE TITLE
[BUG] Schema Manager Bug- Repeat FK Column 

### ISSUE THREAD

**Issue by carloscv97** [DataflareApp/Dataflare#40]
### Describe the bug

![image](https://github.com/DataflareApp/Dataflare/assets/59967161/abb7f1ff-7c63-427d-99b3-d99a16206258)

As you can see countrycode is a FK on both tables but when I see the schema, repeat FK Column 4 times per each table

### Platform and Database

```text
Windows 11, Postgres 15.3
```

**Comment by wyhaya** [comment]
@carloscv97 Hi, this bug is fixed in the new version `0.6.1`, can you try again?

**Comment by carloscv97** [comment]
> @carloscv97 Hi, this bug is fixed in the new version `0.6.1`, can you try again?

Yeah, it's fixed, thanks you for the support
