### ISSUE TITLE
[Feature Request] Run filter when pressing enter key

### ISSUE THREAD

**Issue by igorer88** [DataflareApp/Dataflare#47]
## Run filter when pressing enter key 
<img width="590" alt="imagen" src="https://github.com/DataflareApp/Dataflare/assets/6375299/93724dd5-73a3-4dac-8c2f-bb6d4a0c7132">

- Run filter when pressing **Enter Key**, as if the **Apply** button was clicked.

**Comment by wyhaya** [comment]
Thanks, it's done!
