### ISSUE TITLE
[Feature Request] Add column autocomplete suggestions when typing

### ISSUE THREAD

**Issue by igorer88** [DataflareApp/Dataflare#48]
### Describe the solution you'd like

- Actual behavior:
<img width="568" alt="imagen" src="https://github.com/DataflareApp/Dataflare/assets/6375299/bf65dffe-1f2f-40aa-96a5-898b33be9a2f">

- Should be like this:
<img width="550" alt="imagen" src="https://github.com/DataflareApp/Dataflare/assets/6375299/f83dd413-6f6c-4308-b404-9e2e0bacf38a">
<img width="299" alt="imagen" src="https://github.com/DataflareApp/Dataflare/assets/6375299/ae782251-fd0c-4d11-b4da-9ad7340bcabb">

**Comment by wyhaya** [comment]
Thanks, `v1.6.0` has been released!

https://github.com/user-attachments/assets/58187f5f-3efe-4001-8661-3098584c18b0
