### ISSUE TITLE
[Feature Request] Create connection from database url

### ISSUE THREAD

**Issue by egoist** [DataflareApp/Dataflare#5]
### Describe the solution you'd like

So that I don't have to manually enter host, db name, password etc.

**Comment by wyhaya** [comment]
@egoist You can create a new connection by selecting `Import from URL` in the `New Connection` section.

https://github.com/DataflareApp/Dataflare/assets/23690145/61c01026-535b-4d58-a4f8-013705681d0d

**Comment by egoist** [comment]
nice, didn't notice that
