### ISSUE TITLE
[Feature Request]  Display indexes in schema manager

### ISSUE THREAD

**Issue by joprice** [DataflareApp/Dataflare#51]
### Describe the solution you'd like

It would be helpful for query analysis and optimization to be able to quickly glance at the indexes for a table in schema manager

**Comment by wyhaya** [comment]
Thanks, I'll add it.

**Comment by wyhaya** [comment]
Added in the new version (v1.1.0).
![index](https://github.com/DataflareApp/Dataflare/assets/23690145/790d2973-1f82-4c68-98c8-cd4d0104f945)
