### ISSUE TITLE
[Feature Request] Add Cloudflare D1 database connection

### ISSUE THREAD

**Issue by jasongitmail** [DataflareApp/Dataflare#55]
### Describe the solution you'd like

This would be great! https://developers.cloudflare.com/d1/ 

Based on SQLite 

Might require their [@miniflare/d1](https://www.npmjs.com/package/@miniflare/d1) client lib, not sure. ([Basic example query](https://miniflare.dev/storage/d1)).

**Comment by wyhaya** [comment]
Thanks @jasongitmail 

To connect to the remote D1 database, it seems that only this [API](https://developers.cloudflare.com/api/operations/cloudflare-d1-query-database) is available.

I have added a simple integration that should be available in the next version.
![D1](https://github.com/DataflareApp/Dataflare/assets/23690145/4db62e83-ea55-450d-b737-ca137040a70a)

**Comment by jasongitmail** [comment]
Very cool! Thanks!

**Comment by wyhaya** [comment]
New version released! 
These features are currently unavailable because D1 disables the running of certain SQL.
1. Schema Manager
2. Column input suggestions in SQL editor about
3. More...

**Comment by jasongitmail** [comment]
Thanks! This works great.

One improvement would be to show the column type (number, blob, etc) next to the col name, like you do for other database types:

<img width="726" alt="" src="https://github.com/DataflareApp/Dataflare/assets/50032291/3c7c7a0d-4878-42c3-ac56-b428ea6f4e36">
