### ISSUE TITLE
[BUG] Unsupported value

### ISSUE THREAD

**Issue by wyhaya** [DataflareApp/Dataflare#59]
#### MySQL

* BIT
* GEOMETRY

#### PostgreSQL
* TSQUERY
* Custom Type
* ...

#### CockroachDB
* TSQUERY
* GEOMETRY
* Custom Type
* ...

### Platform and Database

```text
MySQL, PostgreSQL, CockroachDB
```

**Comment by fbonilla02** [comment]
I have this bug when i have an array 
![image](https://github.com/DataflareApp/Dataflare/assets/53198057/eb962b9c-0348-4355-8001-ddba38be17c8)
in another managerdb looks like this:
![image](https://github.com/DataflareApp/Dataflare/assets/53198057/16a60203-d06c-432d-b7dc-0e9a2f4c7dd9)

**Comment by wyhaya** [comment]
Thanks @fbonilla02 , we've fixed all the "Unsupported value" in `v1.3.6`.
