### ISSUE TITLE
[Feature Request] Jump from a foreign key to the record in the referenced table

### ISSUE THREAD

**Issue by pantajoe** [DataflareApp/Dataflare#6]
### Describe the solution you'd like

I would like to be able to double click (or with a similar interaction) on a foreign key of a record in one table. This double click would ideally open the referenced table in a new tab with a pre-filled in query.

Example:

1. I open the table "comment" that references the "post" table via the foreign key "post_id"
2. I double click on the column (or a specific part of it, or right click) "post_id" of the first "comment" record in the "comment" table
3. The "post" table opens with the filter query pre-filled and executed, so the correct "post" record is shown: "post_id" = '2'

**Comment by wyhaya** [comment]
New version has been released.

https://github.com/DataflareApp/Dataflare/assets/23690145/f10da766-d8d8-4819-bb58-c9bf8c48b1fb
