### ISSUE TITLE
[BUG] Window doesn't expands or compact with double click on title bar

### ISSUE THREAD

**Issue by enrique159** [DataflareApp/Dataflare#60]
### Describe the bug

The problem I have is when I change from external monitor size to my macbook screen size, the app is still expanded like if it still in the expanded monitor, so I double click on the title bar to size it to my macbook screen, but it doesn't do anything. Is king of annoying changing the size of the window draggin the corners multiple times just to have the desired size

### Platform and Database

```text
macOS 13.6.4
```

**Comment by wyhaya** [comment]
Hi @enrique159, thank you for your feedback, this error has been fixed!
