### ISSUE TITLE
[Feature Request] Do not auto connect to the database at startup

### ISSUE THREAD

**Issue by egoist** [DataflareApp/Dataflare#67]
### Describe the solution you'd like

It would be nice if the app shows this window at startup instead of connecting to previously opened database:

<img src="https://github.com/DataflareApp/Dataflare/assets/8784712/3c469f90-1f5e-431f-bc7a-8549ee2e9593" width="400">

**Comment by wyhaya** [comment]
New version has been released(v1.3.1).

<img src="https://github.com/DataflareApp/Dataflare/assets/23690145/943140b8-7032-4102-9aad-43f96b8c2d03" width="400">
