### ISSUE TITLE
[BUG] explain sql script not show

### ISSUE THREAD

**Issue by go-gritsanapong-pun-nxz-group** [DataflareApp/Dataflare#69]
### Describe the bug

When I run SQL 
```SQL
EXPLAIN SELECT ...
```
It not show result but it will show 
```
0 rows affected
```
<img width="979" alt="image" src="https://github.com/DataflareApp/Dataflare/assets/143983473/83f190ea-8af0-4fad-94f3-bcbef6836de1">

### Platform and Database

```text
Postgres v14
```

**Comment by wyhaya** [comment]
Thanks, this bug will be fixed in the next version.

**Comment by wyhaya** [comment]
New version(v1.3.2) has been released!
