### ISSUE TITLE
[Feature Request] Open the "public" schema for postgres databases per default

### ISSUE THREAD

**Issue by pantajoe** [DataflareApp/Dataflare#7]
### Describe the solution you'd like

Currently, when I open a new (or existing) postgres connection, the schema "pg_catalog" (or whichever is the first one when all available schemas are sorted alphabetically).

However, as this schema is probably not the one, people want to see, it would be great if the schema "public" would be selected per default.

**Comment by wyhaya** [comment]
@pantajoe Thanks! Completed in next version.

```typescript
const defaultSchema = (config: DatabaseConfig): string => {
    switch (config.type) {
        case DatabaseType.Sqlite:
        case DatabaseType.DuckDB: {
            return 'main'
        }
        case DatabaseType.Postgres: {
            return 'public'
        }
        case DatabaseType.MySql:
        case DatabaseType.MariaDB: {
            return config.options.database || ''
        }
        case DatabaseType.MsSql: {
            return 'dbo'
        }
    }
}
```

**Comment by pantajoe** [comment]
Awesome, thanks! ❤️
