### ISSUE TITLE
[BUG] Horizontal scrolling bar disappears

### ISSUE THREAD

**Issue by danielqba** [DataflareApp/Dataflare#70]
### Describe the bug

When entering a table with many columns, the horizontal bar won't show. I have to press the right arrow in the keyboard and then it shows up. This is only after updating Dataflare to 1.3.1.

### Platform and Database

```text
Ubuntu 24.04, Postgresql, DataFlare v 1.3.1
```

**Comment by wyhaya** [comment]
In v1.3.1 we customized the scrollbar to only show the scrollbar when the container is `scrolling`.
We will fix it in the next version!

**Comment by wyhaya** [comment]
New version(v1.3.2) has been released!
