### ISSUE TITLE
[BUG] thread 'main' panicked at

### ISSUE THREAD

**Issue by facu-alba** [DataflareApp/Dataflare#71]
### Describe the bug

![image](https://github.com/DataflareApp/Dataflare/assets/47679766/6dd708cc-7555-4f7c-9ff1-4cb22501ad44)

![image](https://github.com/DataflareApp/Dataflare/assets/47679766/e18fcb39-53d6-4b23-8f3a-bc8468df7e2f)

I got the error when try to run dataflare: thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.3/src/lib.rs:2021:55:
called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: X11 server connection timed out because it was unreachable"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Any help? Thank you!

### Platform and Database

```text
Ubuntu 22.04.4 LTS, MySQL 8.0.36-0ubuntu0.22.04.1
```

**Comment by wyhaya** [comment]
Thanks @facu-alba , I will release a new version tomorrow to fix this bug!

**Comment by wyhaya** [comment]
hi @facu-alba , Dataflare just released a new version and this bug should be fixed, can you try again?

**Comment by facu-alba** [comment]
![image](https://github.com/DataflareApp/Dataflare/assets/47679766/52808f53-975b-4c84-b4fd-e1d29568806b)


@wyhaya now works! Thank you!
