### ISSUE TITLE
[Feature Request] Custom API Domain for D1 Connections

### ISSUE THREAD

**Issue by OnurGvnc** [DataflareApp/Dataflare#76]
My team accesses the Cloudflare API (api.cloudflare.com) through a custom reverse proxy domain due to some security requirements (the path part remains identical to the Cloudflare domain). This setup allows us to generate user-specific custom tokens, enabling us to manage access more effectively.

Could you please add an optional field for specifying a custom API domain for D1 Connections?

Thank you very much for your work.

**Comment by wyhaya** [comment]
@OnurGvnc Do you just want to change `api.cloudflare.com`?

![host](https://github.com/DataflareApp/Dataflare/assets/23690145/850c7112-42dc-48a0-b1d3-3b84a26f06f7)

```
# Before
https://api.cloudflare.com/client/v4
/accounts/{account_identifier}/d1/database/{database_identifier}/query

# After
CUSTOM_HOST/client/v4//accounts/{account_identifier}/d1/...
```

Do you need something like this? If so, it will be in the next version.

**Comment by OnurGvnc** [comment]
Perfect! This is exactly what we needed. Thank you so much. 🙏

**Comment by wyhaya** [comment]
@OnurGvnc  Dataflare `v.1.3.4` has been released, try it out!

**Comment by OnurGvnc** [comment]
@wyhaya I just tried it, and it's exactly what I needed! Thank you so much. Dataflare is the perfect app I've been looking for.
