### ISSUE TITLE
[BUG] Extension info doesn't load

### ISSUE THREAD

**Issue by igorer88** [DataflareApp/Dataflare#77]
### Describe the bug

The extension for ipv4r doesn't load the extension's description.

<img width="396" alt="imagen" src="https://github.com/DataflareApp/Dataflare/assets/6375299/fca0f2a4-74a8-45e7-a309-565fe805265f">

### Platform and Database

```text
macOS 14.0, Postgres 16
```

**Comment by wyhaya** [comment]
@igorer88 Hi, could you try run this SQL and see what result you get?
```sql
SELECT name, comment FROM pg_available_extensions
WHERE name = 'ip4r';
```

**Comment by igorer88** [comment]
@wyhaya Hi, here it is:
<img width="426" alt="imagen" src="https://github.com/DataflareApp/Dataflare/assets/6375299/b3c72612-5865-4215-9476-566ae69debf9">

**Comment by wyhaya** [comment]
> but maybe the interface should tell there is no comment on that extension

Great idea! It will be displayed in the next version.
