### ISSUE TITLE
[Feature Request] Support for viewing Vectors

### ISSUE THREAD

**Issue by anudit** [DataflareApp/Dataflare#78]
### Describe the solution you'd like

I have a Postgres instance running [Pgvector](https://github.com/pgvector/pgvector). Would love to be able to preview vectors too, currently it shows `Unsupported Value`.

![image](https://github.com/DataflareApp/Dataflare/assets/12015553/6179fd79-fb85-466b-94dc-ffd0328953a1)

**Comment by anudit** [comment]
Freakin awesome work with Dataflare btw @wyhaya !

**Comment by wyhaya** [comment]
@anudit `vector` , `vector[]` will be supported in the next release.

![vector](https://github.com/DataflareApp/Dataflare/assets/23690145/afd6690a-24d3-4564-aed8-5ed006871039)

**Comment by anudit** [comment]
Uninstalling DBVisualizer now, Looking forward to it @wyhaya !

**Comment by wyhaya** [comment]
Just released `v1.3.5`, this error has been fixed!

**Comment by anudit** [comment]
@wyhaya Thanks! I run into `error returned from database: no binary output function available for type vector` on Postgres + https://github.com/tensorchord/pgvecto.rs 
![image](https://github.com/DataflareApp/Dataflare/assets/12015553/dcb79955-1a26-4dc7-96f6-f5d8126efa19)

**Comment by wyhaya** [comment]
Just released `v1.3.6`, this error has been fixed!
