### ISSUE TITLE
[BUG] Select from "set" does not work

### ISSUE THREAD

**Issue by Sukaato** [DataflareApp/Dataflare#79]
### Describe the bug

```sql
set @json='
[
  {"name":"Laptop", "color":"black", "price":1000},
  {"name":"Jeans",  "color":"blue"}
]';

select * from json_table(@json, '$[*]' 
  columns(
   name  varchar(10) path '$.name',
   has_price integer exists path '$.price')
) as jt;
```

Actual:
| # | name   | has_price |
| - | -------- | ---------- |
| 1 |             | 0             |
| 2 |             | 0             |

Expected:
| # | name   | has_price |
| - | -------- | ---------- |
| 1 | Laptop | 1             |
| 2 | Jeans   | 0             |

### Platform and Database

```text
Windows 11
MariaDB 11.1.2
Dataflare 1.3.4
```

**Comment by wyhaya** [comment]
`v1.3.6` has just been released and this bug has been fixed.
