### ISSUE TITLE
[BUG] Postgres `point` col type shows as `unsupported value`

### ISSUE THREAD

**Issue by jasongitmail** [DataflareApp/Dataflare#8]
### Describe the bug

<img width="186" alt="Screenshot 2023-10-26 at 8 21 27 PM" src="https://github.com/DataflareApp/Dataflare/assets/50032291/1a52377b-26e4-49d6-9fdc-fd8c64ae8ff1">

Schema:
<img width="328" alt="Screenshot 2023-10-26 at 8 22 14 PM" src="https://github.com/DataflareApp/Dataflare/assets/50032291/a83fec68-3e38-4fc6-852a-c9ed267e8d5b">

As an example, in Table Plus a point is shown in this format: `(xx.xxxxxxx,yy.yyyyyyyy)`.

### Platform and Database

```text
Postgres 15.4 on NeonDB.
```

**Comment by wyhaya** [comment]
@jasongitmail Thanks. 
There are still some types that are not resolved and are currently displayed as `unsupported value`.
```
TODO: "POINT", "LSEG", "PATH", "BOX", POLYGON", "LINE", "LINE[]" ...
```

**Comment by 2Pacalypse-** [comment]
Just in case it's not on your list already, this also shows up for `CITEXT` values:

![image](https://github.com/DataflareApp/Dataflare/assets/4757944/3e74678d-4ec7-4428-9522-f479773b83d0)

**Comment by wyhaya** [comment]
@jasongitmail A new version has been released that now supports PostgreSQL [geometric](https://www.postgresql.org/docs/current/datatype-geometric.html) types.

@2Pacalypse- `CITEXT` will be supported in the next version (I forgot to add it).

---
There are some unsupported values, which can be viewed in #59.

**Comment by jasongitmail** [comment]
Works great! Thanks for the update!
