### ISSUE TITLE
[Feature Request] Formatting numbers

### ISSUE THREAD

**Issue by Sukaato** [DataflareApp/Dataflare#80]
### Describe the solution you'd like

```sql
SELECT 1 + 1358395738 AS count
```

Actual:
| # | count           |
| - | :------------- |
| 1 | 1358395739 |

Expected:
| # | count              |
| - | :--------------- |
| 1 | 1 358 395 739 |

based on [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) it can be easy to add number formatting

**Comment by wyhaya** [comment]
Related: #56

**Comment by wyhaya** [comment]
Thanks @Sukaato !

`v1.8.2` has just been released, and numbers will now be formatted using `Intl.NumberFormat`, which is related to the currently selected language.

<img width="360px" src="https://github.com/user-attachments/assets/b51d5a52-6de2-45eb-b0eb-c9a4e62cf876" />
