### ISSUE TITLE
[Question] Run cte query in query section

### ISSUE THREAD

**Issue by bearberror** [DataflareApp/Dataflare#86]
### What is your question?

I would like to know how to run query with CTE expression for example,
`WITH cte as (
    SELECT .......
) SELECT * FROM cte WHERE .....`

Result return only WITH clause but not the SELECT clause

**Comment by wyhaya** [comment]
Hi @bearberror , Thanks for your feedback, this is a bug.

We incorrectly parsed this SQL as “execute”, which discarded the query result.

This bug will be fixed as soon as possible.

**Comment by wyhaya** [comment]
Just released [v1.4.0](https://github.com/DataflareApp/Dataflare/releases/tag/v1.4.0), this bug is fixed!

<img src="https://github.com/DataflareApp/Dataflare/assets/23690145/a0911241-0648-4187-901b-b2cbb5e2ea36" width="400" />
