### ISSUE TITLE
[BUG] RQLite connection returns 404

### ISSUE THREAD

**Issue by alexgreendesign** [DataflareApp/Dataflare#88]
### Describe the bug

The app is able to connect to an external RQLite db, and correctly returns the list of tables. On clicking a table it correctly shows the rows count, but does not show the rows. It displays:

Response: HTTP Status: 404 Not Found, Message:

I checked all the requests made via wireshark, and they all worked when called via curl, including the call to select the rows.

### Platform and Database

```text
macOS 14.4, RQLite 7.14.2
```

**Comment by wyhaya** [comment]
Hi @alexgreendesign, Dataflare support rqlite from version `v7.18.0` at minimum.

Dataflare accesses the database in some places through rqlite’s `Unified Endpoint` HTTP API, which was added in version v7.18.0 of rqlite.

* [Unified Endpoint](https://rqlite.io/docs/api/api/#unified-endpoint)
* [rqlite CHANGELOG](https://github.com/rqlite/rqlite/blob/master/CHANGELOG.md#v7180-may-18th-2023)

Although we could achieve the same effect using `/db/execute` or `/db/query` to be compatible with lower versions of rqlite, it’s not really worth it. Especially in Query, where users can execute arbitrary SQL statements, it’s difficult to decide which API to call. For us, the Unified Endpoint is the best option.

**Comment by alexgreendesign** [comment]
Ah okay, that makes sense, thanks.
