### ISSUE TITLE
[BUG] Postgres `enum` col type shows as `unsupported value`

### ISSUE THREAD

**Issue by jasongitmail** [DataflareApp/Dataflare#9]
### Describe the bug

<img width="419"  src="https://github.com/DataflareApp/Dataflare/assets/50032291/007ee562-aacd-4e62-be0a-1c72062d112e">

Schema:
<img width="318"  src="https://github.com/DataflareApp/Dataflare/assets/50032291/780d016b-6f3a-4e94-8cc8-7614b45a2d2b">

### Platform and Database

```text
Postgres 15.4 on NeonDB.
```

**Comment by wyhaya** [comment]
Thank you for your feedback! We just released a new version, and this issue should be resolved. Can you please try again?

**Comment by jasongitmail** [comment]
Working now!
