### ISSUE TITLE
[Feature Request] Default column width wide enough to show name and type

### ISSUE THREAD

**Issue by jasongitmail** [DataflareApp/Dataflare#90]
### Describe the solution you'd like

When launching the app, or maybe when clicking to view a table, set column widths wide enough so that the full name and type can be read.

### Why?

Quality of life feature. Reduces the need to resize columns as frequently, given that column widths currently reset to the default size when relaunching the app (which is fine).

**Comment by wyhaya** [comment]
Now there is a menu that can do this for a single column, and it may become the default value or an optional configuration in the future.

https://github.com/user-attachments/assets/98b4bef3-59a6-4d6a-a259-cb5a696679c2

**Comment by jasongitmail** [comment]
That's cool, but to clarify, my original request was for the column to be wide enough to show the column name and type by default (not the content width.) 

- what you show in the video seems useful and probably the context menu and double clicking on the separator bar (like Excel), is probably ideal. 
- but content could be very wide or narrow, and setting width based on name and type might be a better default bc it ensures the critical info is always fully visible by default

**Comment by wyhaya** [comment]
`v1.8.2` has just been released, and will now display the full column names and types.

* If possible, prioritize using the adjusted width.
* Otherwise use the measured width. `pk? + column name + data type`
* Minimum not less than `140px`.

**Comment by jasongitmail** [comment]
Just upgraded. Looks great! Thanks
