### ISSUE TITLE
[BUG]  Token error on Schema Manager with MSSQL

### ISSUE THREAD

**Issue by kodaicoder** [DataflareApp/Dataflare#91]
### Describe the bug

Before latest update schema manager  with MSSQL didn't have any problem
but after update I got this error

Token error: 'Incorrect syntax near '.'.' on server [DATABASENAME] executing on line 6 (code: 102, state: 1, class: 15)

### Platform and Database

```text
Windows 11 
version 23H2
OS Build 22635.2915


Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   
Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  
Enterprise Edition: Core-based Licensing (64-bit) 
on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)
```

**Comment by wyhaya** [comment]
@kodaicoder Thank you! A new version `v1.7.1` has just been released to fix this bug.
