### ISSUE TITLE
[Feature Request] Support view table support (in sqlite/libsql)

### ISSUE THREAD

**Issue by wldbest** [DataflareApp/Dataflare#97]
### Describe the solution you'd like

I created a view using an existing table and it doesn't show up in the table list. 
Sometimes it is important to see the view table, and I would like to see this feature implemented. For reference, the view looks fine in Turso's default client (drizzle Studio).

I am using libsql(Turso)/sqlite, windows 10.
Thank you.

**Comment by wyhaya** [comment]
Hi @wldbest, I have basically completed it. Next, I just need to test it and then release the new version.

![view](https://github.com/user-attachments/assets/5398280a-e9ca-403b-92c1-c7ee84d46ab8)

**Comment by wyhaya** [comment]
New version (v1.7.3) released
