### ISSUE TITLE
[Feature Request] No timezone indication

### ISSUE THREAD

**Issue by probablykasper** [DataflareApp/Dataflare#98]
### Describe the solution you'd like

MariaDB `TIMESTAMP`s are shown as a datetime in a non-local timezone, without any indication of what timezone Dataflare decided to display it with. Since timestamps are points in time, it would be great if Dataflare could specify which timezone is used, or use the local timezone

**Comment by wyhaya** [comment]
Hi, @probablykasper, thank you for your suggestion!

Dataflare does not specify a timezone by default; it should follow the server's configuration. Starting from Dataflare `v1.8.2`, you can use `Initial SQL` to configure the timezone.

```
Manage Connections -> Your Connection -> Tab(Initial SQL)
```

![init](https://github.com/user-attachments/assets/d032e3d5-1b2a-499a-9290-60a5f18f7484)

**Comment by probablykasper** [comment]
That's nice, but still pretty confusing approach. There's still no indication of a value's timezone. Does this edit some setting in the database itself?

I would understand if the value is a timezone-less datetime, but in this case it's a timestamp. It would be great if the whole value could be displayed

**Comment by wyhaya** [comment]
> That's nice, but still pretty confusing approach. There's still no indication of a value's timezone.

Dataflare is not responsible for setting the time zone; it only displays the values returned by the server.

> Does this edit some setting in the database itself?

No, it is limited to the current session (current connection) and does not affect any settings in your database.

> I would understand if the value is a timezone-less datetime, but in this case it's a timestamp. It would be great if the whole value could be displayed

I noticed that the MariaDB documentation explicitly states that TIMESTAMP is always stored in UTC time and converted to the session timezone upon retrieval, so the final timezone used may come from the database settings or the connection session settings.

The value received by Dataflare does not include a timezone; it is merely a Date + time that may have undergone timezone conversion.

https://mariadb.com/kb/en/timestamp/#time-zones

**Comment by probablykasper** [comment]
Ah ok, thanks for explaining. Seems like pretty bad design by MariaDB
